### ISSUE TITLE
Feed.createPost() fails

### ISSUE THREAD

**Issue by thegostep** [robin-thomas/erasure-sdk#19]
```
const postOut = await feed.createPost({ data: 'hello'})
console.log('postOut', postOut)
```

`Error: argument is not an iterator or iterable`

**Comment by robin-thomas** [comment]
@thegostep Because you are calling the function wrong: https://github.com/robin-thomas/erasure-sdk/blob/master/src/erasure/ErasureFeed.js#L98

If you want it to have the `{ data: data, proofhash: proofhash }` format, then I'll change it over to that.

**Comment by thegostep** [comment]
oh... its not a object. I missed that
