### ISSUE TITLE
getObject() fails with proofhash as base58 and hex

### ISSUE THREAD

**Issue by thegostep** [robin-thomas/erasure-sdk#20]
hex --> `Error: invalid address (arg="address", value="0xa8b89246132a14cfe68a65c50b10b297743cd4c", version=4.0.43)`
base58 --> `Error: network does not support ENS (operation="ENS", network="kovan", version=4.0.43)`

**Comment by robin-thomas** [comment]
@thegostep Can you share your code sample?

At the moment, it supports only `base58` hash to `getObject()`. So if that's also failing for you, I wanna see your code to get some idea.

**Comment by thegostep** [comment]
```
const postOut = await feed.createPost({ data: 'hello' })
console.log('postOut', postOut)

const post = await this.state.erasure.getObject(postOut.post.proofhash())
```

**Comment by thegostep** [comment]
in this code sample both functions fail

**Comment by robin-thomas** [comment]
@thegostep First function will fail. Because you are calling the function wrong as mentioned here: https://github.com/robin-thomas/erasure-sdk/issues/19

So you are not passing a valid proofhash to `getObject`. Anyway, I have added a check for validity.

**Comment by thegostep** [comment]
This is still failing for me: https://github.com/erasureprotocol/erasure-bay/commit/8a7b7dc36b55af5644e90d8c4455cc0e786a25b8#diff-14b1e33d5bf5649597cdc0e4f684daddR137-R140
