### ISSUE TITLE
Token contract is initialized with wrong provider

### ISSUE THREAD

**Issue by thegostep** [robin-thomas/erasure-sdk#26]
https://github.com/robin-thomas/erasure-sdk/blob/315fd1de6731952e70bc4564bdeed6376457f8b5/src/factory/Escrow_Factory.js#L41

Should pass ethers signer

**Comment by robin-thomas** [comment]
This is something I fixed yesterday. Just havent merged it yet,
https://github.com/robin-thomas/erasure-sdk/pull/21

Had been facing an esm issue with test coverage. Had fixed that yesterday. So will be improving the tests and coverage now.
