### ISSUE TITLE
Post.checkStatus() causes exception

### ISSUE THREAD

**Issue by thegostep** [robin-thomas/erasure-sdk#8]
```Uncaught (in promise) Error: overflow (operation="setValue", fault="overflow", details="Number can only safely store up to 53 bits", version=4.0.43)```

```
    const feedAddress = '0x119F364f3E4cACcBa985d2309d19E618AC79102F'
    console.log('getFeed', feedAddress)

    const post = await this.state.erasure.getObject(feedAddress)
    console.log('post', post)

    const postOwner = post.owner()
    console.log('postOwner', postOwner)

    const postStatus = post.checkStatus()
    console.log('postStatus', postStatus)

    const submissions = await post.getPosts()
    console.log('submissions', submissions)

    console.log(await submissions[0].checkStatus())
```

https://github.com/robin-thomas/erasure-sdk/blob/953f891d849ca50efd119904f6b8e6c4cdd34fbe/src/erasure/ErasurePost.js#L330

seems like this is calling a function which does not exist

**Comment by robin-thomas** [comment]
```
const feedAddress = '0x119F364f3E4cACcBa985d2309d19E618AC79102F'
console.log('getFeed', feedAddress)

const post = await this.state.erasure.getObject(feedAddress)
console.log('post', post)
```

@thegostep If you are passing `feedAddress` to the `getObject()` function, why are you expecting it to be a post object?

**Comment by thegostep** [comment]
i just named the feed object post

**Comment by thegostep** [comment]
`checkStatus()` causes infura request to fail:

`POST https://ipfs.infura.io:5001/api/v0/get?arg=QmaGV55FvMyyq4mvMwB3kyjbLXC2V1NbbmwAopr3DJVz2R 504`

**Comment by robin-thomas** [comment]
@thegostep No. The request is supposed to fail.
It's trying to retrieve the `keyhash` to determine if the post has been revealed or not.

Gateway will timeout when there is nothing in IPFS to retrieve, meaning the post has not been revealed.
